# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='activate_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
