# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20181102_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.DeleteModel(
            name='zhuce_wz',
        ),
    ]
