# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoshuo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
