# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 06:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutanMing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='海贼团名')),
            ],
            options={
                'verbose_name': '团名',
                'verbose_name_plural': '团名',
            },
        ),
        migrations.CreateModel(
            name='zeiwang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('set', models.BooleanField(default=True)),
                ('guoshi', models.CharField(max_length=30, verbose_name='果实')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '人物信息',
                'verbose_name_plural': '人物信息',
            },
        ),
        migrations.AddField(
            model_name='tutanming',
            name='zeiwang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.zeiwang'),
        ),
    ]
