# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12, verbose_name='名字')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('mima', models.CharField(max_length=12, verbose_name='手机号')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
