# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 06:21
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('liuyan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
    ]
